### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by scooter-dangle** [rust-dc/fish-manpage-completions#15]
Should run `cargo test` and verify that `cargo fmt` doesn't make changes.

**Comment by AlanSwenson** [comment]
Can i use travis for this?

**Comment by necaris** [comment]
I've personally lost some faith in the reliability of Travis after they laid off a lot of their dev staff -- have also been wondering about the new open-source https://builds.sr.ht/ service. But 👍 for using Travis / Circle / etc for getting started quickly, we can migrate later if at all.

**Comment by AlanSwenson** [comment]
great, ill set this one up then on Travis and we can change it later if we want
