### ISSUE TITLE
Add flag to perform an in/out verify against a preëxisting good in/out

### ISSUE THREAD

**Issue by scooter-dangle** [rust-dc/fish-manpage-completions#3]
Necessary for seeing how far off we are from replicating the original.

**Comment by pickfire** [comment]
```
cargo r -- -v2 -zs fixtures/docker-rmi.1
```

I believe this is fixed, although progress bar is not there yet. There might be some minor differences since the original one does not seemed that correct to me either, not sure if we want a bug-for-bug port.
