### ISSUE TITLE
Links to synopsis / droff standards

### ISSUE THREAD

**Issue by tj800x** [rust-dc/fish-manpage-completions#8]
https://unix.stackexchange.com/questions/17833/understand-synopsis-in-manpage
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09

**Comment by tj800x** [comment]
Oooh.  Grapse is an online manpage editor.  Very cool for understanding what is going on.

http://roperzh.github.io/grapse/

These does a pretty good job of explaining troff/groff.  The plan_9 page goes into depth.

https://liw.fi/manpages/
http://doc.cat-v.org/plan_9/misc/man_page_writing_howto

This presentation pdf is a pretty good overview, but doesn't go into a ton of detail on the Options section (The one I think we need to understand the most).

http://web.archive.org/web/20060102165607/http://people.debian.org/~branden/talks/wtfm/wtfm.pdf

From this documentation it should be possible to generate a list of manpage elements that need to be parsed.

**Comment by tj800x** [comment]
So, it looks likes options is not a "standard" section...more like a customary practice.

https://lists.gnu.org/archive/html/groff/2018-11/msg00031.html

The best documentation seems to be groff_mdoc(7).  I'm not sure how old the one on my Macbook manpages is, but it seems to be substantial.  



Here we go.  This seems to be 

https://www.freebsd.org/cgi/man.cgi?query=mdoc.samples

**Comment by scooter-dangle** [comment]
Haven't looked through all the links yet, but that Grapse link in particular looks super useful :+1:

**Comment by pickfire** [comment]
@tj800x Is there a reason why we need to link to synopsys / droff standards?
