### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by pickfire** [rust-dc/fish-manpage-completions#82]
Should we do something like cargo which is quite verbose especially we have small tasks (I have ~10000 man pages to be generated)? Or should we use something like [indicatif](https://crates.io/crates/indicatif) which is able to be used with rayon (see also #50)?

**Comment by charliethomson** [comment]
I looked into indicatif the other day, it looks really good. definitely has my vote

**Comment by scooter-dangle** [comment]
Resolved by #111
